// Code generated by "stringer -type=ServerType"; DO NOT EDIT

package inter

import "fmt"

const _ServerType_name = "AccountServerCharServerZoneServer"

var _ServerType_index = [...]uint8{0, 13, 23, 33}

func (i ServerType) String() string {
	i -= 1
	if i < 0 || i >= ServerType(len(_ServerType_index)-1) {
		return fmt.Sprintf("ServerType(%d)", i+1)
	}
	return _ServerType_name[_ServerType_index[i]:_ServerType_index[i+1]]
}
